// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bplcjxijmmdhehjioqlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbGNqeGlqbW1kaGVoamlvcWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNzgyNDUsImV4cCI6MjA4NjY1NDI0NX0._LkQYITWmR2OUodrtoKUCmLKXFHLx6L197dCD51K57Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});